### ISSUE TITLE
carousel starts on last item 

### ISSUE THREAD

**Issue by mauroc** [harakisgeorge/carouselreact#1]
I have an item array of 3 elements
At initial page render: 
- displays the last item of the array. 
- The left arrow has no effect.
- the right arrow slides image to the left, but shows no new image/description . The left arrow brings it back to the last item
additional info
- the radio buttons render correctly 
- the activeIndex state variable is updated correctly (starts at 0 then goes to 1 and 2 as I click the right arrow, than back to 0 as I click left)
So it seems to be a problem with the rendering of the "inner" div. The translate style starts at 0%, then -100% and -200%

I am not familiar with the translate attribute. Any idea what the problem may be?
Too bad coz it's a great app. So much more flexibility than some of the packages available

**Comment by mauroc** [comment]
![image](https://user-images.githubusercontent.com/859182/233681694-bb576d7a-0e9d-453d-ada0-45b81a1f1887.png)

**Comment by mauroc** [comment]
turns out I have some spurious .scss files in my directory , and one of them was setting margin-right to -100%. I have no idea why, but turning that off in chrome console fixes the issue. Not sure why the .scss is there , but it's not an issue with your code. Thanks

**Comment by mauroc** [comment]
FYI - I found that there are .carousel, .carousel-item etc classes in bootstrap that interfere with the ones your app uses. That's where the scss classes were coming from!

**Comment by harakisgeorge** [comment]
haha sorry friend, I am not very active on my personal github due to my full time job github. Also unfortunately not as active as I wanted to be with my older youtube videos. There is so much new stuff coming all the time that I want to cover new stuff all the time :)
